python train.py \
    --workers 8 \
    --device 0 \
    --batch-size 20 \
    --data data/coco.yaml \
    --img 640 640 \
    --cfg cfg/training/yolov7.yaml \
    --weights '' \
    --name yolov7 \
    --hyp data/hyp.scratch.p5.yaml \
    --epochs 1